### ISSUE TITLE
Accomodate cancelled inserts via Postgres Triggers

### ISSUE THREAD

**Issue by stavro** [elixir-lang/ecto#1067]
Using Ecto 1.0, I have a Postgres table which has an associated `before insert` trigger.  This trigger filters out and discards some (based on complicated criteria) insertions.

However, all inserts from Ecto raise a `StaleModelError` if an id was not returned.  I cannot find any way to avoid this behavior.

To set up:

```sql
create table tests (id serial primary key);

create or replace function cancel() returns trigger as $$
begin
  return null;
end $$ language plpgsql;

create trigger cancel_insert before insert on tests for each row execute procedure cancel();
```

```elixir
defmodule Test do
  use Ecto.Model

  schema "tests" do
  end
end

%Test{} |> Repo.insert
```

And the error returned is:
```
** (Ecto.StaleModelError) attempted to insert a stale model:

%Test{__meta__: #Ecto.Schema.Metadata<:built>, id: nil}

    (ecto) lib/ecto/repo/model.ex:259: Ecto.Repo.Model.apply/4
    (ecto) lib/ecto/repo/model.ex:83: anonymous fn/10 in Ecto.Repo.Model.do_insert/4
```

I think there might be a few things worth thinking about here:
  * Why are we raising `Ecto.StaleModelError` when optimistic locking is not implemented for this model?
  * How can a new model (via an `insert`) ever be considered stale?
  * An optional way to disable returning an `id`, or at least a way to gracefully accept an error message without raising an exception

Would love to hear your thoughts!

**Comment by josevalim** [comment]
> How can a new model (via an insert) ever be considered stale?

We never expected that cause to be triggered. Although we can fix the issue for insert, it is impossible for us to make a distinction between a failed trigger and a failed update, isn't it? Or does Postgrex return the proper information?

**Comment by stavro** [comment]
I can't think of a scenario where an insert / update itself would fail to complete without some sort of error message being returned (such as invalid column name).

So in this scenario we attempted to insert a single row, Postgres didn't complain about any errors, and returns a response of `INSERT 0 0` indicating there nothing actually inserted - but it doesn't provide information as to why there was nothing inserted. The same would be true for updating.

For comparison on the same insert with ActiveRecord (no error returned):

```ruby
> Test.create()
   (0.2ms)  BEGIN
  SQL (1.4ms)  INSERT INTO "tests" DEFAULT VALUES RETURNING "id"
   (0.2ms)  COMMIT
=> #<Test id: nil>
```

**Comment by stavro** [comment]
(I've updated my previous response with a little more detail.)

After thinking about it a little, the best route forward may be to raise the `Ecto.StaleModelError` only if:
  * The given model has **opted into** Optimistic Locking,
  * The operation is an **update** or **delete**, and
  * The number of rows returned is zero.

In all other cases, load the returned changes (if present) into the model struct and return the struct.

Would you be open to this behavior?

**Comment by josevalim** [comment]
@stavro my concern is that we would support aborting triggers only on insert... why it would theoretically make sense on update/delete too. So while I agree raising StaleModelError is not a good idea, I think we should still raise something.

**Comment by stavro** [comment]
I think an error for these scenarios should only ever be raised if you **opt into** Ecto's implementation of Optimistic Locking.

> my concern is that we would support aborting triggers only on insert

Using the above (3) rules would allow Ecto to work seamlessly with aborting triggers for inserts, updates, and deletes (with no error being raised) EXCEPT in the case of a model with optimistic locking.  It's not unreasonable to require users of Ecto to be careful when implementing a version tracking mechanism and also specialized postgres triggers at the same time.

**Comment by josevalim** [comment]
It is not about optimistic locking only. If you try to update an ID that has been deleted, we need to error out as well.

**Comment by stavro** [comment]
> It is not about optimistic locking only. If you try to update an ID that has been deleted, we need to error out as well.

I see.  I was misunderstanding the use case of the error.  Maybe perhaps this should be a default, but overridable behavior?  ActiveRecord, for instance, does not raise an error for inserts, updates, or deletes in which an indication of `0 rows` were affected is returned.

The response of an insert or update operation (eg, `INSERT 0 1`) is not 100% reliable to determine whether or not a row was inserted.

Some more example usage patterns where the "affected row count" cannot be trusted:
  * **Trigger-based partitioning**. http://stackoverflow.com/a/1011329 and http://stackoverflow.com/a/12169992 . (A trigger re-routes the insert to a partitioned table. Every insert will return `INSERT 0 0`).
  * **Trigger-based upsert** (for < Postgres 9.5) http://digitalitility.com/tutori-alitility/postgresql/create-an-upsert-trigger/

**Comment by josevalim** [comment]
Thank you. I am still skeptical about supporting this by default, I would raise as today. You can then just rescue the particular exception in your cases if you are sure it is an expected case for you. Thoughts?

**Comment by josevalim** [comment]
Closing this per the previous discussion.

**Comment by ephe-meral** [comment]
Hi, I've implemented soft-deletes in Postgres as described in the [**Trigger-based soft-deletes**](http://shuber.io/porting-activerecord-soft-delete-behavior-to-postgres/) link from @stavro above - it works for all standard DB operations except for Repo.delete and Repo.delete! where it returns the `StaleEntryError` as described above - Ecto also reverts the change in the `deleted_at` field because of the delete being executed in a transaction...

However, I realized that the `delete_all` function works, since it accepts the result from Postgres that is returned by the trigger and doesn't do a rollback afterwards. I was wondering if this is the default behaviour and whether I should just be using `delete_all` everywhere then, or whether this could be fixed within `delete`

**Comment by josevalim** [comment]
@ephe-meral this is tricky. Maybe we could have an option called `on_stale: :raise_and_rollback | :accept` that would you pass to delete. The first value is the default. However, if you are implementing soft-delete, maybe it makes more sense to use `delete_all` indeed.

**Comment by ephe-meral** [comment]
So you'd also opt for `delete_all`, @josevalim? I was also wondering whether or not it might make sense to support any soft delete strategy within Ecto natively...

**Comment by josevalim** [comment]
@ephe-meral for now i would go with delete-all because that means no code. But if you think it has limitations, then please let us know. :)

**Comment by narrowtux** [comment]
In case someone finds this in 2018 and wants to implement polymorphic foreign keys, I have a solution where you don't need to use insert_all/update_all.

Normally, your trigger for this kind of use case would be `BEFORE INSERT`, use an `INSERT INTO` to insert the data into the correct inherited table and `RETURN NULL` at the end so postgres doesn't duplicate the data in the main table. 

However, if you do this, an `INSERT INTO` on the main table will always result in `INSERT 0 0`, which ecto doesn't like and it will raise a StaleEntryError. 

We can trick ecto into thinking its new row was actually inserted by moving the trigger to after the insert has happened (with `AFTER INSERT`), and the first thing we'll do is delete the new row before we insert it ourselves. Obviously, you must be careful to limit your delete so it will actually only delete that one row.

That way, the database will still return `INSERT 0 1`, which makes ecto happy, and in the end, the data will end up in the correct inherited tables. 

I'm not sure how you would use this workaround for soft-deletes though, since all the `ON DELETE`s will have been triggered after the delete has happened.
