### ISSUE TITLE
Fragment interpolation and sigil questions

### ISSUE THREAD

**Issue by parkerl** [elixir-lang/ecto#1089]
I have been playing around with fragments after a few questions came up on Slack. Queries using `fragment` fail to compile with either of the following:

Interpolation with a variable.
```
    clause = "1 = ?"
    from p in "posts", where: fragment(^clause, 1)
```

With a sigil.
```
    from p in "posts", where: fragment(~S|1 = 1|)
```

Confusingly, an interpolated value with no variables does compile. However, neither the Postgres or MySQL adapter will allow interpolated values in fragments.

```
      clause = "1 = ?"
      from p in "posts", where: fragment(^clause)
```

Should either of the top two be supported?

**Comment by josevalim** [comment]
The first should not be supported because it leads itself to SQL injection. The second could be supported but it don't see much purpose. To support it, we could simply call Macro.expand on the first argument of fragment and check if it returns a keyword list or a string. The third should raise at compile time, and implementing the previous suggestion should be enough to make it raise.

Thanks for the report! :)

**Comment by parkerl** [comment]
@josevalim just to clarify should we...

- Raise a better error message for the first case? The current error is `fragment(...) expects the first argument to be a string for SQL fragments, a keyword list, or an interpolated value, got: '^clause'` which seems to imply interpolated fragments are ok. This should also take care of the confusion around the last case.

- Sigils might be too edge case. The only case I an make for them is if you need to write a regex or `like` that matches on double quotes. `fragment("ILIKE '\"'")` maybe looks better as `fragment(~S{ILIKE '"'})` and it would seems expected that a sigil should work where a string dose. 

(As a side note, some of this came up from someone trying to use a regex with a `?`. I am going to also make a PR documenting the escaping of that case in `fragment`)

**Comment by josevalim** [comment]
> Raise a better error message for the first case? The current error is fragment(...) expects the first argument to be a string for SQL fragments, a keyword list, or an interpolated value, got: '^clause' which seems to imply interpolated fragments are ok. This should also take care of the confusion around the last case.

Oh, an interpolated value is OK if it is a keyword list. So if there is an interpolated value, we need to check at runtime if it is a keyword list and raise otherwise. We did a similar trick in a previous PR we were working on.

> Ignore sigils as too edge case.

It is fine to support sigils. Call `Macro.expand(first_arg, caller | env)` before the check and it should become a string just fine.

**Comment by parkerl** [comment]
@josevalim great. I will get on this as soon as I can.

**Comment by josevalim** [comment]
Awesome, thank you!

**Comment by parkerl** [comment]
Sorry  for the delay. I am working on this but I have been too busy to finish it off.

**Comment by josevalim** [comment]
There is no rush. :) thanks for the heads up!
