### ISSUE TITLE
Public API to turn Ecto.Query structs into the query they represent

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ecto#1096]
Right now, there's no public API that given an `%Ecto.Query{}` struct returns the actual query as a string:

```elixir
# named to_string or whatever
query = from u in User, where: u.email == "my email"
Ecto.Query.to_string(query)
#=> "SELECT FROM users WHERE email == 'my email'"
```

I think it would be useful for a number of possible use cases (mine is wrapping `Ecto.Repo` and doing stuff with the query before and after it's been performed).

**Comment by josevalim** [comment]
I think we have a to_sql in the Ecto.Adapters.SQL module, no?

On Monday, November 23, 2015, Andrea Leopardi <notifications@github.com>
wrote:

> Right now, there's no public API that given an %Ecto.Query{} struct
> returns the actual query as a string:
>
> # named to_string or whateverEcto.Query.to_string(from u in User, where: u.email == "my email")#=> "SELECT FROM users WHERE email == 'my email'"
>
> I think it would be useful for a number of possible use cases (mine is
> wrapping Ecto.Repo and doing stuff with the query before and after it's
> been performed).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1096>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment]
@josevalim Only works for SQL adapters of course.

**Comment by josevalim** [comment]
Yes, it needs to be adapter specific. Some adapters do not even have a
string representation.

On Monday, November 23, 2015, Eric Meadows-Jönsson <notifications@github.com>
wrote:

> @josevalim <https://github.com/josevalim> Only works for SQL adapters of
> course.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1096#issuecomment-159015027>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
It doesn't have to be a string, it can just return the query that the adapter sends to the database. Why does it have to be adapter specific, we can add it to one of the adapter behaviours.

**Comment by michalmuskala** [comment]
I'm afraid it won't be that easy with MongoDB. Query struct does not contain params, and we can't generate a query without them - there are no parameters in Mongo's query syntax.

**Comment by ericmj** [comment]
I'm pretty sure we can supply params in this case.

**Comment by josevalim** [comment]
Can we update the proposal then? I would like to know:

1. What we are going to call a function that receives a query and returns whatever the query is supposed to be for the given adapter

2. Where should this function exist. It cannot exist in Ecto.Query because we need the repository (so we get the adapter). If we need it in the repository, **why** is it important enough to be in the repository and not just in the adapter like today.

Thanks folks. :)

**Comment by ericmj** [comment]
It's fine if it's on the adapter (not on the repo) as long as it's a generic interface for all adapters (hence on one of the behaviours).

**Comment by josevalim** [comment]
@ericmj I honestly wouldn't like to impose user facing API to the adapters which otherwise are only internal. I don't want to teach folks to rely on those APIs because I would like to retain the liberty of changing it any time. In other words, :-1: for conflating the current adapter behaviour with user functions.

It is ok for the adapter itself to expose it, because they are assuming this responsibility, I just don't want developers to access Ecto.Adapters.PostgreSQL.insert (for example) and assume it won't ever change. It will because it is an internal Ecto requirement. It goes through a different cycle than the user APIs.
