### ISSUE TITLE
Raise if embedded_schema is given and an association is defined

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1166]

**Comment by tony612** [comment]
Do you mean the situations like these two? Are there other situations I missed in your opinion? 
```elixir
# situation 1
defmodule Author do
  use Ecto.Schema

  schema "authors" do
    # This is wrong! A schema can't associate with a embedded schema.
    has_one :wrong_profile, WrongProfile
  end
end

defmodule WrongProfile do
  use Ecto.Schema

  embedded_schema do
    field :name
  end
end
```
and
```elixir
# situation 2
defmodule Author do
  use Ecto.Schema

  schema "authors" do
    embeds_one :wrong_profile, WrongProfile
  end
end

defmodule WrongProfile do
  use Ecto.Schema

  embedded_schema do
    # This is wrong! The embedded schema can't use association functions.
    belongs_to :author, Author
  end
end
```

**Comment by michalmuskala** [comment]
I think the main issue would be using a `has_one` or `has_many` relation inside `embedded_schema` - such a relation makes no sense (how would you fetch the relation?).
`belongs_to` inside `embedded_schema` could have some applications so we should probably allow it. One example would be: post -> embeds many comments -> belongs to author.

**Comment by josevalim** [comment]
@tony612 yes, that's exactly the case. :)

@michalmuskala we don't support loading those cases now anyway, so we should just raise on all of them.

**Comment by tony612** [comment]
@josevalim ok, cool. I'll try to finish this in these two days.

**Comment by tony612** [comment]
Hi, @josevalim . I think I met a problem when trying to implement situation 1.

If I define a function `__schema__(:embedded)` to indicate if it's a embedded schema(true for `WrongProfile`). Then I can't find a good way to do the check for the module which defines association(`Author`) because it's a runtime function.
But if I just use `Module.get_attribute`, it seems `WrongProfile` being in compile time can't be guaranteed.

It there any solution for this problem?

**Comment by josevalim** [comment]
I think we could do it all at compile time. If embedded_schema is called, set `@ecto_embedded true` and raise if any of the association functions are called.

**Comment by tony612** [comment]
@josevalim This way works for situation 2. But for situation 1, we need to get `ecto_embedded ` attribute of `WrongProfile` when `has_one` is called in Author. But it doesn't work, I just got error like `could not call get_attribute on module Ecto.AssociationTest.Post because it was already compiled`

**Comment by josevalim** [comment]
@tony612 ah, we are doing only one side, only when you call from the embedded model. situation 1 would be hard to solve indeed.

**Comment by tony612** [comment]
@josevalim Got it. So that will be much easier :)
