### ISSUE TITLE
Include the type that failed to cast in changeset error

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#1295]
If a field fails to cast in a changeset the error is simply: `[field: "invalid"]`.

It should be: `[field: "invalid, expected value of type datetime"]` to help users fix their error.

**Comment by josevalim** [comment]
I don't think this would be helpful for users sending data through a form,
for example.

On Sunday, March 6, 2016, Eric Meadows-Jönsson <notifications@github.com>
wrote:

> If a field fails to cast in a changeset the error is simply: [field:
> "invalid"].
>
> It should be: [field: "invalid, expected value of type datetime"] to help
> users fix their error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1295>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment]
I don't think it would be worse than simply "invalid".

**Comment by michalmuskala** [comment]
Given that the message is intended to be shown to the end user, I'm not sure we should use words like "type" or "datetime". 
If we want to help developers maybe we should consider simply logging with debug level every time we return `:error` from `Ecto.Type.cast`? We could show the value we got and expected type.

**Comment by ericmj** [comment]
You have to also consider that end users are API consumers. Seeing "invalid" does not help me in any way to solve the error. We also should not log because we should not log user errors.

**Comment by josevalim** [comment]
Because of the reasons raised, we are not going to support it directly in Ecto. You can, however, support it in your app by calling `Ecto.Changeset.traverse_errors` and translating "is invalid" messages into messages that contain the type information.

**Comment by wojtekmach** [comment]
Thanks for your consideration, I think using `traverse_errors` here makes sense.

> You can, however, support it in your app by calling Ecto.Changeset.traverse_errors and translating "is invalid" messages into messages that contain the type information.

I started looking into it, and right now `traverse_errors` accepts a fun, `msg_fun`, that takes `{msg, opts}`. So, in order to convert "is invalid" to a message that contains type information, we need to grab that type information from somewhere within `msg_fun`. I thought about these options:

1. have `msg_fun` accept: `{field, type, msg, opts}`
2. have `msg_fun` accept: `{field, msg, opts}`. This is shorter, and would also work better for non-column errors for which we don't have type information (e.g. `add_error(changeset, :foo, "bar")`). However, in order to get the type information for column fields, we'd need to use `__schema__` or other stuff like that within `msg_fun`. Which would get tricky (if not impossible) for embeds and assocs, because the `field` in `msg_fun` would need to somehow reference to which schema that field belongs too so we could get type information.
3. have `msg_fun` accept: `{field, msg, opts}` where `field` could be `field` or `{field, type}` and the `msg_fun` would need to handle both cases.

WDYT? Perhaps there're simpler ways of solving this?

**Comment by josevalim** [comment]
Actually, we have a better option now. All error messages are now of the format "{String.t, Keyword.t}" this means that we could pass the type information in the error message:

    {"is invalid", type: :string}

Then Ecto can look for this key and do the proper interpolation. Thoughts?

**Comment by wojtekmach** [comment]
I like this a lot, cleaner and backwards-compatible.
