### ISSUE TITLE
Connection error after rescuing Ecto.InvalidChangesetError

### ISSUE THREAD

**Issue by stavro** [elixir-lang/ecto#1347]
### Environment

* Elixir version: 1.2
* Database and version: Postgres 9.4
* Ecto version: 1.1.5
* Database adapter and version: Postgrex 0.11.1
* Operating system: OS X

### Current behavior

If you rescue an `Ecto.InvalidChangesetError` during a transaction, the Repo becomes unreachable until the transaction ends.

All calls to the Repo will error with `:noconnect`.

Demo: https://gist.github.com/stavro/46c92a9ebc2d5648f07eb81eb15e3558

Since ExUnit wraps tests within a transaction, it's difficult to test any behavior around rescuing constraint errors. :(

### Expected behavior

A better error message telling me why I can't use the connection or a restored connection.

**Comment by fishcakez** [comment]
Nested transactions that raise force a rollback and so the connection is no
longer available for the duration of the transaction. I don't think we can
change the failure in 1.1 because people might be catching the exit reason.

The error is much improved in 2.0. I believe a DBConnection.Error with
message "transaction is rolling back" is raised.

**Comment by josevalim** [comment]
Perfect, closing this then as it is fixed in 2.0. :)
