### ISSUE TITLE
Wrap DB errors as ChangeSet erros

### ISSUE THREAD

**Issue by alexeypetrushin** [elixir-lang/ecto#1352]
I inserted a model in database with the code below and the app get crashed. 
It would be better to handle this error as `{:error, reason}` instead of throwing an error.

```
case Repo.insert MyModel.changeset %MyModel{}, params do
  {:ok, _} -> ...
  {:error, _} -> ...
end
```

The error:

```
** (Postgrex.Error) ERROR (string_data_right_truncation): value too long for type character varying(255)
    (ecto) lib/ecto/adapters/sql.ex:496: Ecto.Adapters.SQL.model/6
    (ecto) lib/ecto/repo/schema.ex:297: Ecto.Repo.Schema.apply/5
    (ecto) lib/ecto/repo/schema.ex:81: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:477: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/9
    (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/3
    (ecto) lib/ecto/adapters/sql.ex:582: Ecto.Adapters.SQL.transaction/8
    (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:551: Ecto.Adapters.SQL.transaction/3
```

**Comment by josevalim** [comment]
I don't think we should put it inside the changeset. I would actually like to know when those cases show up so we properly convert it to a changeset validation. Relying on the database specific checks is the only option sometimes but using changesets validations will provide the best user experience and performance.

**Comment by alexeypetrushin** [comment]
In my understanding the statements like code below should **never** crash, unless something really unforeseened happened:

```
case do_something() do
  {:ok, _} -> ...
  {:error, _} -> ...
end
```

There's an error handler and yet it still crashed. Why? Because there are not only the "standard" errors but there's also another "special" kind of error. 

Why introduce complexities and two types of errors?

**Comment by michalmuskala** [comment]
The `{:ok, _}`/`{:error, _}` is not about handling any errors - it's about handling expected errors. Failing a validation or a database constraint is an expected error - this happens often and is in general the result of user actions. That's why you get an `:error` tuple back.

On the other hand an arbitrary error from the database is *not* expected. In general you can't do anything about such errors other than crash the process. Such errors most often signify an error made by the programmer - this is an exceptional situation. That's why an exception is raised.
