### ISSUE TITLE
Add some documentation RE ecto_repos configuration

### ISSUE THREAD

**Issue by robconery** [elixir-lang/ecto#1380]
Just this morning I was having a play with rc.0 and it broke when I tried to create a migration:

```
warning: could not find repositories for application :physics.

You can avoid this warning by passing the -r flag or by setting the
repositories managed by this application in your config files:

    config :physics, ecto_repos: [...]

The configuration may be an empty list if it does not define any repo.

** (Protocol.UndefinedError) protocol Enumerable not implemented for :ok
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1486: Enum.reduce/3
    (elixir) lib/enum.ex:609: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

The warning is fine, but as you can see Ecto seems to be trying to read in the config bits anyway. I was able to fix the problem by following the warning advice (good one!), but this left me confused as to what was supposed to be where in the config and Repo itself.

Everything works, but the configuration seems a bit redundant:

```elixir
config :physics, Physics.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "redfour",
  username: "rob"

config :physics, ecto_repos: [Physics.Repo]
```

Also, I should add that the `samples` are out of step which I'm sure you know, just wanted to be sure you knew it.

**Comment by josevalim** [comment]
Thank you @robconery!

This is indeed a bug. I have fixed it earlier today and added a test.

> Everything works, but the configuration seems a bit redundant:

Yes, I agree there is some redundancy. We decided to go with an explicit mechanism because sometimes you may want to run tasks for a repository in sibling application. For example, if we break a phoenix application in web and a sibling project, you may still want to create and migrate the Physics.Repo when running the web application tests.

> Also, I should add that the samples are out of step which I'm sure you know, just wanted to be sure you knew it.

I did not, thank you! We should probably include its tests in the build. I will leave this open until it is fixed.

**Comment by josevalim** [comment]
Fixed in master!
