### ISSUE TITLE
Asserting New Error Format?

### ISSUE THREAD

**Issue by jamescmartinez** [elixir-lang/ecto#1445]
With the pre 2.0 version of Ecto, I had the following code:

```elixir
assert {:username, "can't be blank"} in errors_on(%User{}, %{username: nil})
```

where `errors_on` looked like this:
```elixir
def errors_on(model, data) do
  model.__struct__.changeset(model, data).errors
end
```

but now, with the new format of errors, I get the following error from my assertion:
```elixir
Assertion with in failed
     code: [:username, "can't be blank"] in errors_on(%User{}, %{username: nil})
     lhs:  [:username, "can't be blank"]
     rhs:  [username: {"can't be blank", []}]
```
(note the `rhs` is what is now returned from the changeset errors in Ecto 2.0).

How can I assert that my changeset contains `{:username, "can't be blank"}` now? I've tried various configurations of maps and keyword lists. I'm brand new to Elixir, so be gentle. :)

**Comment by wojtekmach** [comment]
@jamescmartinez you can manually extract the errors in your `errors_on` function, perhaps something like this:

```elixir
errors |> Enum.map(fn {field, {message, _opts}} -> {field, message} end)
```

You can also look into `Ecto.Changeset.traverse_errors/1` which allows you to conveniently pluck out error messages from a changeset with a function.

P.S. please follow the issue template and not use the tracker for support requests. Instead, ask questions on SO/ML so that any answers given will be available to broader audience and the Core team can focus on real issues.

**Comment by jamescmartinez** [comment]
Thanks @wojtekmach, I'll close this issue and use SO or the ML. Sorry!
