### ISSUE TITLE
Transactions raise on failure when using the sandboxed test adaptor

### ISSUE THREAD

**Issue by howleysv** [elixir-lang/ecto#1459]
### Environment

* Elixir 1.2.5, OTP 18.3
* Postgres 9.4
* ecto 2.0.0-rc.5
* postgrex 0.11.1
* OSX 10.11.5

### Current behavior

With this function:
```
def tx_insert(username) do
  Repo.transaction fn ->
    %User{}
      |> cast(%{username: username}, [:username])
      |> unique_constraint(:username)
      |> Repo.insert
  end
    |> case do
      {:ok, {:ok, _}} -> true
      _ -> false
    end
end
```

I get this behaviour in iex:
```
iex(1)> tx_insert("foo")
true
iex(2)> tx_insert("foo")
false
```

But when running in a test, the failed transaction raises:

```
test "tx test" do
  assert true == tx_insert("foo")
  assert false == tx_insert("foo")  # Raises
end
```

```
** (Postgrex.Error) ERROR (in_failed_sql_transaction): current transaction is aborted, commands ignored until end of transaction block
```

### Expected behavior

Test passes

**Comment by fishcakez** [comment]
This bug highlights two differences in behaviour when using the sandbox with postgresql and does not occur in other SQL backends (or none that have adapters).

Firstly Postgres will ROLLBACK on COMMIT if transaction is aborted. This means we should always track the last sync status and if committing a savepoint transaction we should rollback if the last status was `:failed` instead of `:transaction`.

Secondly we run into this problem when doing single queries as an error in a single query will be inside the sandbox transaction when using the sandbox. We can resolve this by introducing `on_error_rollback: boolean` (or better name, default to false) that works like `ON ERROR ROLLBACK` feature in `psql`. I don't know how it works but we can duplicate this efficiently (and it is probably the same) with the following psuedo protocol messages as a batch:

```
begin savepoint
execute query
release savepoint
sync
```

If the query errors the release savepoint is ignored and we get an error, we can then rollback/release send this batch:
```
rollback savepoint
release savepoint
sync
```
If there isn't an error we have released the savepoint and continue as normal. with introducing roundtrips or much overhead.

This feature would also work explicitly inside or outside the sandbox and would be much more efficient than doing it by hand.

**Comment by fishcakez** [comment]
> If there isn't an error we have released the savepoint and continue as normal. with introducing roundtrips or much overhead.

Importantly that should be WITHOUT

**Comment by josevalim** [comment]
@fishcakez 

* for the transaction modes one I believe somewhere in the Ownership or Sandbox pool we dont pass owership checkout options to the handle_begin call
* we need to make sure we dont set mode: :sandbox inside a savepoint transaction. only when inside the sandbox transaction but not a savepoint transaction. we also need to let people set mode: :sandbox inside the savepoint transaction

**Comment by josevalim** [comment]
I have just pushed a test that guarantees this is fixed although I haven't yet done the mode changes yet (see commit above).
