### ISSUE TITLE
Add transaction isolation level option to Repo.transaction

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#1460]
Today you can set the transaction level by calling out `Ecto.Adapters.SQL.query`. It's a bit inconvenient and becomes more arduous when using `Ecto.Multi`:

```elixir
{:ok, value} = MyRepo.transaction(fn ->
  Ecto.Adapters.SQL.query(MyRepo, "SET TRANSACTION ...", [])
  MyRepo.transaction(multi)
end)
```

With an option:

```elixir
{:ok, value} = MyRepo.transaction(multi, isolation: "...")
```

**Comment by fishcakez** [comment]
It would be more efficient to make this change at the driver level where we can set the isolation level using a transaction mode as part of BEGIN, instead of doing separate queries. We can build on top of the existing `mode: :transaction | :savepoint`, its almost as if this option was named with this in mind.

This will also allow us to set the isolation level on ownership checkout.

**Comment by fishcakez** [comment]
AH, my suggestion would only allow us to set the isolation level for the whole transaction, I guess someone might want more tuning than that. For example it would not work when using nested transactions or savepoint "transactions" :(.

**Comment by ericmj** [comment]
I think it's fine to raise if a nested transaction changes isolation level:

> The transaction isolation level cannot be changed after the first query or data-modification statement

**Comment by ericmj** [comment]
NVM, it would break test transactions.

**Comment by fishcakez** [comment]
> I think it's fine to raise if a nested transaction changes isolation level:

I am not sure what would happen if we had
```
Repo.transaction(fn() -> Repo.transaction(fn() -> ... end) end)
```
> NVM, it would break test transactions.

It woudn't if we overloaded `mode` because we force `mode: :sandbox` when using the sandbox pool in transactions, and isolation level could need to be set on checkout (which would just work if  `mode: ..` was passed as an option).

So I think we could go ahead with a driver level approach?

**Comment by ericmj** [comment]
It's very hard to set transaction isolation level even with `Ecto.Adapters.SQL.query(MyRepo, "SET TRANSACTION ...", [])` because in tests you almost always have some setup that inserts data before calling your application code. This will cause the `SET TRANSACTION` call to fail because you cannot do any queries before it.

I don't know how to solve this. The alternative would be to not set the isolation level in tests but it feels bad to not test this at all.

/cc @josevalim

**Comment by fishcakez** [comment]
@ericmj if we support the isolation/mode option at the driver level for normal transaction it would be to possible to set the isolation level on ownership checkout with Ecto.Adapters.SQL.Sandbox.checkout(Repo, opts). `opts` get passed to the sandbox proxy and it would pass the options to `handle_begin` at the driver level and `handle_begin` would get the options.

**Comment by josevalim** [comment]
We have decided to not support this feature due to how it plays with nested transactions in Ecto. If you are setting conflicting levels, we need to raise, and the only way to do so is by issuing a separate query, which would deny the benefits we would get from implementing this at the adapter level in the first place.

**Comment by mguimas** [comment]
@josevalim It has passed more than two years since this feature was requested, and Ecto might have changed in the meantime to make it easier to implement. Can this be reopened, or would implementing it require a substantial and risky refactoring?

**Comment by josevalim** [comment]
The constraints are the same. The other thing is that serialization level is also very DB dependent, so it is hard for Ecto to "normalize" it. Keep in mind though you can set the level yourself today by calling `Repo.query!` inside the transaction:

    Repo.transaction(fn ->
      Repo.query!("SET TRANSACTION ...", [])
      ...
    end)

**Comment by mguimas** [comment]
@josevalim And what is the default isolation level, if "SET TRANSACTION ..." is not executed? Is the database default level, or is it determined by the ecto adapter?

**Comment by josevalim** [comment]
Per database.

**Comment by zachdaniel** [comment]
A custom version could be implemented in your own repo fairly easily too.

```
defmodule MyApp.Repo do
  ...
  def transaction(func, opts \\ []) do
    super(fn ->
      isolation = opts[:isolation]
      if isolation do
        query!("SET TRANSACTION ?", [isolation])
      end
    end, opts)
  end
end
```

**Comment by mguimas** [comment]
@zachdaniel `super` does not seem to work as `Repo.transaction/2` is not overridable.

**Comment by zachdaniel** [comment]
Ah, that is a pain. You could give it its own name, like `isolated_transaction/3` that explicitly takes an isolation level.
