### ISSUE TITLE
left join preload with without distinct returns wrong number of rows

### ISSUE THREAD

**Issue by ramhoj** [elixir-lang/ecto#1478]
### Environment

* Elixir version: Elixir 1.2.3
* Database and version: psql (PostgreSQL) 9.4.4
* Ecto version (mix deps): 1.1.5
* Database adapter and version: postgrex 0.11.1
* Operating system: Mac OS X 10.11.4 (El Capitan)

### Current behavior

```elixir
from users in User,
  left_join: subscriptions in assoc(users, :subscriptions),
  preload: [subscriptions: subscriptions]
```

Will not return duplicates while:

```elixir
from users in User,
  left_join: subscriptions in assoc(users, :subscriptions),
  preload: [:subscriptions]
```

will.

Is this expected behaviour?

If the first example is combined with a limit the number of result will be less than the limit even if the total number of rows are greater than the limit.

They all generate the same SQL (execept for the extra columns when preloading with the join):
```sql
SELECT
  u0.\"id\", u0.\"token\", u0.\"icloud_ref\", u0.\"name\", u0.\"role\", u0.\"blocked\", u0.\"block_reason\", u0.\"inserted_at\", u0.\"updated_at\", u0.\"team_id\"
FROM
  \"users\" AS u0
LEFT OUTER JOIN
  \"subscriptions\" AS s1 ON s1.\"user_id\" = u0.\"id\"
```

Adding `distinct: users.id` removes the discrepancy (and duplicates)

### Expected behavior

I expected a `:left_join` to return duplicates if the left table has several rows per right table independent of the `:preload` statement.

**Comment by josevalim** [comment]
Yes, that's expected behavior. When you preload in the first case, Ecto is
going to merge all duplicate entries. In the second one, Ecto is doing two
queries, one for fetching all users and another for fetching preloads. If
you want to keep duplicates, then you likely don't want to use preload at
all. For example:

from users in User,
  left_join: subscriptions in assoc(users, :subscriptions), select:
{users, subscriptions}




-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by bartblast** [comment]
@josevalim I think this behaviour is very counter intuitive, I found myself with the exact same problem, I didn't know what was going on... I expected the same thing as @ramhoj . 

Is it documented? The only related doc I found is this:
https://hexdocs.pm/ecto/Ecto.Query.html#preload/3
"(...) Therefore, instead of returning number_of_posts * number_of_comments results, like a join would, it returns only posts with the comments fields properly filled in. (...)"
but in my opinion it doesn't describe this situation. Maybe it makes sense to state it explicitly in the docs that duplicates are removed?
