### ISSUE TITLE
Tracking down "no process" error

### ISSUE THREAD

**Issue by BinaryMuse** [elixir-lang/ecto#292]
Hey, guys,

I'm running Ecto 0.2.3 on a cluster of four machines. Occasionally, one of the nodes gives me the following error:

```
2014-10-01 16:44:21.231 [error] GenServer #PID<0.150.0> terminating
Last message: {:query, "SELECT r0.\"id\", r0.\"uuid\", r0.\"script_hash\", r0.\"started\", r0.\"ended\", r0.\"active\", r0.\"node\", r0.\"label\"\nFROM \"recordings\" AS r0\nWHERE (r0.\"active\" = TRUE)\nORDER BY r0.\"started\" DESC", [], 5000}
State: %{conn: #PID<0.592.0>, monitor: nil, params: [port: 5432, decoder: #Function<15.98203264/4 in Ecto.Adapters.Postgres.prepare_start/2>, username: "xxxxxxx", password: "xxxxxxx", hostname: "xxxxxxx", database: "xxxxxxx"]}
** (exit) exited in: :gen_server.call(#PID<0.592.0>, :stop, :infinity)
    ** (EXIT) no process
2014-10-01 16:44:21.232 [error] GenServer RecagentExecutor.Server terminating
Last message: {:recording_list, [page: 0]}
State: %{autostop_timer: nil, pid: nil, uuid: nil, working: false}
** (exit) exited in: :gen_server.call(#PID<0.150.0>, {:query, "SELECT r0.\"id\", r0.\"uuid\", r0.\"script_hash\", r0.\"started\", r0.\"ended\", r0.\"active\", r0.\"node\", r0.\"label\"\nFROM \"recordings\" AS r0\nWHERE (r0.\"active\" = TRUE)\nORDER BY r0.\"started\" DESC", [], 5000}, 5000)
    ** (EXIT) time out
```

Trying the request again gives the same error with different pids. I'm having trouble figuring out how I might track down the cause of the problem. Near as I can tell, Ecto is calling `Postgrex.Connection.stop` [in `terminate`](https://github.com/elixir-lang/ecto/blob/fffe9335a980e6e39a4dc0784b7973bcbd871814/lib/ecto/adapters/postgres/worker.ex#L123) and the "no process" exception comes [from there](https://github.com/ericmj/postgrex/blob/bb12d101b659d3383eb8c701f975ce20ec64c46a/lib/postgrex/connection.ex#L70).

The query is:

```elixir
defp get_sub_list(active) do
  query = from r in Recording, where: r.active == ^active, order_by: [desc: r.started]
  RecagentLibrarian.Repo.all(query)
end
```

I have my Repo supervised as such:

```elixir
defmodule RecagentLibrarian do
  use Application

  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    children = [
      worker(RecagentLibrarian.Repo, [], restart: :permanent)
    ]

    opts = [strategy: :one_for_one, name: RecagentLibrarian.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

Any help or hints in the right direction would be greatly appreciated.

**Comment by josevalim** [comment]
@ericmj is there work to be done on this? Should I assign it to you?

**Comment by ericmj** [comment]
I have not started on it and don't have time to work on it near feature. PRs appreciated!

**Comment by fishcakez** [comment]
This can be partially solved by switching from poolboy to sbroker[1]. With sbroker a worker asks for work (in poolboy terms must check itself in) only when it is ready to handle work. This means a disconnected worker would never be called allowing for a simpler connection backoff implementation (i.e. no timers) and no client blocks waiting for the worker it checked out to connect.

Poolboy is very well proven and simple , and sbroker is neither, so without compelling proof a switch would be ill advised. I can do a write up but it would take > 10 times longer than the change itself so I would like to know before hand if it is worth doing.

Related notes:
* sbroker uses PropEr for tests, which is licensed with GPL. When packaged in hex PropEr and related test code is not included.
* Workers using sbroker must contain sbroker specific code so there is a certain amount of lockin.
* sbroker has optional features to handle overload and self tune the worker pool size.

**Comment by ericmj** [comment]
sbroker could possibly be an improvement for ecto, but I feel it's slightly orthogonal to this issue. sbroker would make it less likely the issue arises, but am I correct in that you could still call a process that has crashed?

We are going to move from poolboy in the future because for our needs poolboy requires a separate worker process which means a lot of additional message passing.

**Comment by fishcakez** [comment]
Sorry I think you are right, I was saw the network issue comments and about implementing dropoff and thought it might be useful given that context. I am unsure if it could even make it less likely?

Looking at the code and the logs more closely I would guess that `RecagentExecutor.Server`, `Ecto.Adapters.Postgres.Worker` and `Postgrex.Connection` all time out at about the same time because they all have the same time out running (either through `GenServer.call` or a timer).

Unfortunately the connection process exits with reason `:normal`[1] in this case so an error doesn't appear in the logs. It is strange to exit with reason `:normal` when an error has occurred and also strange to exit with reason `:normal` with pending replies.

The worker process could receive this `:normal` exit before its call times out or it could time out. Either way it raises an exit of the form `{_, {GenServer, :call, _}}`. If the reason is a time out then its a race to see if it can call `stop/1` in time inside its `terminate/2`, otherwise the connection is already dead and `stop/1` will always fail.

A small note that the `alive?` call doesn't prevent the stop failing because the connection could exit after `alive?` and before the `monitor` in the call, it would be better to do something like:
```elixir
try do
  conn && Postgrex.Connection.stop(conn)
catch
  :exit, {:noproc, _}
     :ok
end
```
[1]https://github.com/ericmj/postgrex/blob/250fc158475f2d4a02784534328df714847e1d6f/lib/postgrex/connection.ex#L308

**Comment by josevalim** [comment]
@fishcakez suggestions and other improvements have been pushed to master, thank you!
