### ISSUE TITLE
Custom type inserting/updating changes the value of the field

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/ecto#345]
Ecto changes field's value to the one produced by dump (https://github.com/elixir-lang/ecto/blob/master/lib/ecto/repo/model.ex#L22) which isn't quite convenient. Imagine that you have a JSON field before inserting/updating and then suddenly after that that's a string.

**Comment by josevalim** [comment]
Yes, I need to invoke the "load" callback to custom types which are not being used yet. It is in my plans to do it today! :D

**Comment by maxim** [comment]
Was anything done here? Seeing this in Ecto 1.0.6. /cc @josevalim

**Comment by maxim** [comment]
Specifically, I have custom type with `def type, do: :binary` (it's actually stored as a binary in mysql), but my `load` returns a list of integers, converted from binary data. So when I run Repo.get, everything works, my field shows up as a list of integers. When I run Repo.insert, the model I get has my field in the raw binary state instead of a list. This causes poison to error out, because it's not a valid binary string.

**Comment by josevalim** [comment]
It should work. Have you implemented dump? Can you put your implementation
online?

On Saturday, November 21, 2015, Maxim Chernyak aka hakunin <
notifications@github.com> wrote:

> Specifically, I have custom type with def type, do: :binary (it's
> actually stored as a binary in mysql), but my load returns a list of
> integers, converted from binary data. So when I run Repo.get, everything
> works, my field shows up as a list of integers. When I run Repo.insert, the
> model I get has my field in the raw binary state instead of a list. This
> causes poison to error out, because it's not a valid binary string.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/345#issuecomment-158615104>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by maxim** [comment]
@josevalim looks basically like this (notice how type is binary, but load returns list): https://gist.github.com/maxim/d4d9b940a70060fe82e6

**Comment by josevalim** [comment]
There are a couple confusing things in your custom type implementation. You must only have two representations: the binary (db type) and the list (ecto type) one.

* cast should receive any type and output the ecto type (list)
* dump should receive the ecto type (list) and output the db type (binary)
* load should receive the db type (binary) and output the ecto type (list)

Because your custom type is not obeying those rules, your types are indeed getting messed up. Keep in mind you also don't need to handle nil.

**Comment by maxim** [comment]
@josevalim I so wish I had this comment when I was learning to write a custom type. This was not clear to me from [the docs](https://hexdocs.pm/ecto/Ecto.Type.html), because they use the same type for ecto and database type, and provide no clarification for cases like mine. The only info is in the comments of the example there, and look what it says about "dump".

> load should receive the db type (binary) and output the ecto type (list)

I guess as a side effect of other mess I had list somehow passed into load, so I added a clause to avoid an error.

> Keep in mind you also don't need to handle nil.

What about load for an empty field in db?

**Comment by josevalim** [comment]
> What about load for an empty field in db?

I believe load wouldn't even be called.

Could you please send a pull request to improve the docs? I could swear this information was there, but apparently not so clearly. Thank you. :)

**Comment by maxim** [comment]
Yes, will make PR.

**Comment by maxim** [comment]
Here it is https://github.com/elixir-lang/ecto/pull/1095
