### ISSUE TITLE
Provide an explicit Ecto.DateTime type with casting

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#385]

**Comment by josevalim** [comment]
Then we can discuss about adding custom parsing (or not).

**Comment by briksoftware** [comment]
I can take this. Is it ok if I do it like in Crudex, where the only accepted format is ISO 8601 UTC (so ending with Z or +00:00)? If we have to handle the timezone then we either need to convert to UTC (relatively expensive date arithmetic) or just ignore it since the underlying tuple-based format cannot store the timezone.

Also, in an "encode" (or better to_string) method converting to string would be quite handy, wouldn't it?

**Comment by josevalim** [comment]
ISOz is great as starting point, yeah. A `to_string` function too.
