### ISSUE TITLE
Support configurable timeouts

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#448]
The idea is to store the timeout along side the repository pool:

https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql.ex#L31

Then we need to change the calls to `__pool__` in that same module to consider it now returns a tuple and properly use it instead of `@timeout`.

**Comment by mobileoverlord** [comment]
thanks, I forgot to add

**Comment by briksoftware** [comment]
@josevalim pong.

should the timeout value go in the general repo configuration or where? Should I extend also the URL parser to support parameters like ?timeout=5000&something=... while I am at it?

**Comment by josevalim** [comment]
@briksoftware It should go in the general repo configuration in the config file and read during compilation time. Let's not extend the URL parser for now even because timeout is compile time, so specifying it in the URL shouldn't do anything.

**Comment by briksoftware** [comment]
@josevalim reading the timeout during compilation would be efficient, but this requires the configuration to be available at compilation time. Let's take this example from the tests (extended to have timeout):

```elixir
defmodule NoStorageRepo do
  use Ecto.Repo, adapter: NoStorageAdapter, otp_app: :ecto
end

Application.put_env(:ecto, NoStorageRepo, [timeout: 1000])
```

This cannot work, since the repo is already compiled at the point where Application.put_env is invoked. Moving the line inside of the module declaration of course works (if I read the config in __before_compile__ then even the order is irrelevant), but we cannot predict when the config will be available. 

Or is this behavior acceptable from your point of view?

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by josevalim** [comment]
Oops, I clicked the wrong button. Please disregard last message (deleting both).

**Comment by josevalim** [comment]
It is completely acceptable. The config files are loaded before compilation so we are fine. We just need to document it later though.

**Comment by briksoftware** [comment]
Ok, then you should see a PR in a few hours

**Comment by josevalim** [comment]
Thank you @briksoftware!
