### ISSUE TITLE
Handling empty strings for integers & floats in changesets?

### ISSUE THREAD

**Issue by citizenparker** [elixir-lang/ecto#465]
Hello!

In a Phoenix Controller I update an Ecto model that has a high number of optional integer fields. From an HTML form these fields will come in as empty strings, `""`. I'd love to either translate these to `nil` in Ecto or be treated as if they weren't passed in but I only see two options for doing so now:

1. Sanitize the params before I pass them into the changeset to make this conversion
2. Make my own custom Integer/Float types that do this translation but delegate back to the original type otherwise.

The first approach seems contrary to the purpose of changesets, but the second approach seems like overkill.

Unless I am missing a sensible third option here (likely, I am n00b at all this), I think there are two possible ways to modify Ecto to fix this:

1. Within non-string types, translate empty string to nil during casting. _(seems sensible but perhaps there's an edge case I'm not thinking of)_
2. Add some kind of "translation" hook to changesets or schemas that occurs before casting. _(I can't think of many other use cases for this though.)_

Thoughts?

**Comment by whatyouhide** [comment]
The purpose of changesets is also to validate parameters, so I think it's not contrary to the purpose of changesets to do something like:

```elixir
def changeset(model, params) do
  params = Enum.map(params, fn
    {k, ""} -> {k, nil}
    pair -> pair
  ) |> Enum.into(%{}) 
  # ...
end
```

or something similar. That said, the fact that HTML forms send blank fields as `""` is probably something that could be taken care of by Ecto; however, Ecto has nothing to do with HTML so maybe this should happen at the Phoenix level.

**Comment by josevalim** [comment]
This should be handled by Ecto but I am not sure what is the best way to handle this. Should we scrub those values before calling cast? Maybe by adding a scrub function that removes anything that is an empty binary or an empty list from the map? On the other hand we could say this is a controller responsibility as those attributes are leaking due to HTML. Thoughts?

**Comment by josevalim** [comment]
Ok. This is not an Ecto responsibility. You need a `scrub_params/2` function that should go through all parameters replacing any "" or [] by nil. In fact, we will remove the current blank checks from Ecto and discuss about adding `scrub_params/2` directly to Phoenix. Thank you!

**Comment by martinos** [comment]
In my case, I have a search form on an index page. 

When the form is submitted, the `search` param is set. In the case that the page is used as an index page, the `search` param is not set. In that case, we cannot use the `scrub_params` plug, since the param raises an error.

What is the best way to handle that case?
