### ISSUE TITLE
Example with multiple read slaves

### ISSUE THREAD

**Issue by mcginleyr1** [elixir-lang/ecto#488]
Low priority just want an example with multiple read slaves.  Django has issues with it, so my company uses HAproxy to maintain a pool of read slaves.  With this I want to make sure ecto does that and then have an example of how to do it right.   Let me know if you need more info!

**Comment by josevalim** [comment]
It is super easy!

You just define multiple repositories: `MyApp.Repo`, `MyApp.Repo.ReadSlave1`, `MyApp.Repo.ReadSlave2` up to 4 (or any power of 2). Their configuration is going to be similar and you can easily share them in the `config/config.exs` file.

Now, every time you need to do a read, you just need to do:

```elixir
def repo do
  # size needs to be power of 2 that you care about
  <<at::integer-size(2), _::bits>> = :crypto.rand_bytes(1)
  Enum.fetch! [MyApp.Repo.ReadSlave1, ..., ], at
end
```

Alternatively you can create a facade repository that does exactly that:

```elixir
defmodule Sample.Repo do
  def all(query, options \\ []) do
    read_repos.all(query, options) # Read goes through the random above
  end

  def update(changes, options \\ []) do
    Sample.Repo.Master.update(changes, options) # Those go to master
  end
end
```

So we don't have something out of the box but, because the repository operations, it is very easy to cache or add master/slave setup.

**Comment by josevalim** [comment]
If this technique works for you, it would be awesome if you could write a blog post about it. I think it would help tons of people!

**Comment by mcginleyr1** [comment]
Jose that should, and it's quote obvious I don't know why I didn't think of it.  I'll def work on writing something up!

**Comment by josevalim** [comment]
@mcginleyr1 it is definitely a neat idea, I didn't think about it though, credit goes to @mschae!

**Comment by kenta-polyglot** [comment]
I just published a simple package for multiple read slave.
https://github.com/kenta-aktsk/read_repos

Thanks for information of this issue.
