### ISSUE TITLE
Release Ecto 0.9.0

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#500]
We will be ready to release Ecto 0.9.0 soon as we will merge MySQL support in the next few hours. @mobileoverlord can you please update to master (I have copied you on all changes) and let us know if you are good to go?

Once you tell us you are green on master, we we will get ready for release.

**Comment by mobileoverlord** [comment]
I have ran through the tests and I am encountering two issues.
1.
A majority of the tests which execute on the posts table fail when inserting NULL for the column uuid due to the unique constraint on the column in the model. SQL considers the UNIQUE index to be violated. I can set a where clause on the UNIQUE KEY to only check for unique when not null, but I didn't know how you wanted to handle this default?
2.
https://github.com/elixir-lang/ecto/blob/047fdc70642a49c2cbb7ae6803a955f3850c5bfe/integration_test/cases/repo.exs#L80
It appears that when inserting an empty changeset it attempts to insert into the column id which in mssql cannot be inserted into because it is an identity column (:serial)

**Comment by josevalim** [comment]
Interesting. Why those didn't fail in the past though? Also, can you post
the error for the second one?



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by josevalim** [comment]
For the null one, it requires at least SQL Server 2008. It seems to be a
high restriction to make. Maybe it could be a repository/adapter option we
would set and you would set in your test repos?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by josevalim** [comment]
done!
