### ISSUE TITLE
Consider creating the database on mix ecto.migrate

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#509]
We should support --no-create option to skip it in case we implement this.

**Comment by tony612** [comment]
@josevalim I implement this as https://github.com/tony612/ecto/commit/267c287f131bde5495eb7d324148262c9f5222c2 

But I find it difficult to write the test because I can't find a proper way to mock `Mix.Tasks.Ecto.Create.run/1`.One possible solution is to change the function to `def run(args, migrator \\ &Ecto.Migrator.run/4, creator \\ &Mix.Tasks.Ecto.Create.run/1)`, but it seems a little ugly. Any idea?

**Comment by josevalim** [comment]
I think your approach is ok. :) Please do send a pull request!

**Comment by josevalim** [comment]
Btw, we would need to update the docs too, to mention it creates a database if one wasn't created yet.
