### ISSUE TITLE
Calling preload multiple times, should we use already loaded associations? 

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/ecto#528]
Should we re-query the associations? Or should we use already loaded associations?

**Comment by josevalim** [comment]
This also applies to `Ecto.Model.assoc/2`. If we call it with preloaded associations, should we just use this information instead?

**Comment by paulcsmith** [comment]
I think it should use the already loaded associations. Sometimes I call preload in a function if I know I the association. Sometimes the association is already preloaded before I call the function and sometimes it's not. I wouldn't want it to load the association twice. Especially because the name `preload` would not imply that it reloads the association each time it is called. There could be another function called `reload_association` or an option that is passed to `preload` and `assoc/2`

**Comment by jeregrine** [comment]
Mayve we have an option for preload to force reloading if user wants it.

**Comment by MSch** [comment]
I agree with @paulcsmith, `preload` to me means that it does not reload if called multiple times. If that were the case it should just be called `load`.

It does make sense though to either add `reload` or an option to `preload`. (I tend towards `reload` that either reloads the whole model "tree" or just the association (configured via an option))

I'm not so sure regarding `assoc`.

**Comment by josevalim** [comment]
It cannot apply to `assoc/2` because it always returns a query, so it is about preload only indeed.

**Comment by josevalim** [comment]
In master.
