### ISSUE TITLE
is sql generated in compilation time？

### ISSUE THREAD

**Issue by pynixwang** [elixir-lang/ecto#529]
`from` is a macro. is this standing for the title.

**Comment by ericmj** [comment]
The query expressions in the query struct are generated at compile time but the SQL is not because you can compose queries at runtime so it would be impossible to generate the SQL at compile time.

The issue tracker is for issues, use the mailing list for questions: https://groups.google.com/forum/#!forum/elixir-ecto.

**Comment by josevalim** [comment]
To expand on that, we do as much work at compile time as possible. We are planning to add cache for the runtime work but that wins about 7% to 10% as most of it is at compile time indeed.
