### ISSUE TITLE
Default engine to InnoDB when creating MySQL databases

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#538]
We should make it an option for storage_up as the other existing options and document it.

/cc @laurocaetano @liveforeverx

**Comment by laurocaetano** [comment]
The default storage engine for mysql 5.5+ is `InnoDB`. The older versions use `MyISAM` -> https://dev.mysql.com/doc/refman/5.7/en/storage-engine-setting.html

As far as I know, it is not possible to set the default storage engine when creating the database (but it can be configured in the `my.cnf` file). The only option are setting the current session to use some default engine `SET default_storage_engine=InnoDB` or setting the engine when creating the table `CREATE TABLE test (id serial) ENGINE InnoDB`.

I think it's not a bug because it can be correctly defined by the server configuration.

**Comment by josevalim** [comment]
Let's do the create table configuration then. We can add an option to
table/2 in migration and default to InnoDB in MySQL case!

On Monday, March 23, 2015, Lauro Caetano <notifications@github.com> wrote:

> The default storage engine for mysql 5.5+ is InnoDB. The older versions
> use MyISAM ->
> https://dev.mysql.com/doc/refman/5.7/en/storage-engine-setting.html
>
> As far as I know, it is not possible to set the default storage engine
> when creating the database (but it can be configured in the my.cnf file).
> The only option are setting the current session to use some default engine SET
> default_storage_engine=InnoDB or setting the engine when creating the
> table CREATE TABLE test (id serial) ENGINE InnoDB.
>
> I think it's not a bug because it can be correctly defined by the server
> configuration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/538#issuecomment-84732681>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by laurocaetano** [comment]
That sounds fair to me. I'll work on it.
