### ISSUE TITLE
Make `Ecto.Migration.SchemaMigration` model configurable

### ISSUE THREAD

**Issue by gjaldon** [elixir-lang/ecto#566]
For some context:
https://groups.google.com/forum/#!topic/elixir-ecto/tKtiEpmgcS4

Make `Ecto.Migration.SchemaMigration` model configurable so that users do not need to modify Ecto library code.

**Comment by gjaldon** [comment]
If it's alright, I'd like to take this on @josevalim.

**Comment by josevalim** [comment]
Definitely, thank you for tackling this

**Comment by limhoff-r7** [comment]
Attaching myself to this issue since I was the one requesting it in the Google Group

**Comment by gjaldon** [comment]
@limhoff-r7 will be working on this in the next few days in case you were wondering how soon it would be available. :)

**Comment by josevalim** [comment]
@limhoff-r7 actually, someone pointed out  that using the same table as rails is going to be a really bad idea. Wouldn't it make more sense to just change the table name in your case?

**Comment by limhoff-r7** [comment]
I guess, I don't even need a separate table name if I do the following:

In production, the Rails application will be in charge of running the migrations until the time that we can have separate database like good independent microservices, but right now we can't do that since we also would need to separate the users and authentication into a shared service since we need to read the cookie set by the Rails application, which means reading the user sessions and users that authlogic manages.

So, I guess I can just work around this by having a separate database with duplicate migrations (for Users, UserSessions, etc) in Ecto for unit tests and then for integration tests with the Rails application, the database will be shared, but the Rails application will be in charge of migrations.  (We have a service that runs the migrations when the Rails application starts instead of using rake db:migrate because our Rails application is run on user's laptops, not on servers and the migrations need to happen without the user need to run a separate command first.)

Will Ecto behave correctly without a schema_migrations table that it can read if I don't try to run migrations from phoenix and just point it at an already migrated database?  Like, none of the mix tasks will implicitly try to run migrations?

**Comment by ericmj** [comment]
Nothing runs migrations unless explicitly called.

**Comment by josevalim** [comment]
Ok. I am closing this for now. If you need at least a separate table name, please let us know.

**Comment by proxygear** [comment]
Hello, I run in the same issue.
Except I was planning to have separated databases initially,
now I need to have both rails and ecto connecting the same table on for JOIN purpose.

Waiting for this feature, I will check if I can't configure it from Rails, else I'll hack the source.

Cheers

**Comment by proxygear** [comment]
[My fork](https://github.com/elixir-lang/ecto) with `@table %Ecto.Migration.Table{name: :elixir_schema_migrations}`

**Comment by josevalim** [comment]
We should make the table name configurable. I agree. Please open up an issue that allows us to configure the migration table name. That is much better than making the whole model. :)
