### ISSUE TITLE
How 'bout a `get_all_by/2` and `get_all_by/2`?

### ISSUE THREAD

**Issue by gjaldon** [elixir-lang/ecto#577]
It's great that we now have `get_by/2` and `get_by!/2` thanks to this https://github.com/elixir-lang/ecto/pull/568. 

Do we already have the equivalents of those functions but returns multiple models? If not, I would like to take this on.

**Comment by josevalim** [comment]
I am :-1: . If people feel strongly about this feature then I would rather add keyword support to the query instead of adding more functions to the repo.

**Comment by programisti** [comment]
I think its very useful, every-time I need to do this feature I write queries via `from`
for example if I want to get all `comments` based on `post_id`
I do like this:
```
from(c in Comment, where: c.post_id == ^post_id)
|> Repo.all
```
If we had this feature then I could do this without writing query with `from`:
```
Repo.get_all_by(Comment, post_id: ^post_id)
```

even more, `get_by/2` and `get_all_by/2` should accept keyword list such as 
```
Repo.get_by(Comment, [post_id: 2, published: true])
```

**Comment by michalmuskala** [comment]
You can easily achieve this today with:
```elixir
Repo.all(where(Comment, ^[post_id: post_id]))
```

The repo interface is already quite broad today. That's why we should be extra considerate when expanding it and only do so for things that can't be easily achieved otherwise or those that remove a lot of boilerplate. `get_all_by` is not such case in my opinion.

You can, however, easily define the `get_all_by` function for repos in your application by including the following function definition in the relevant `Repo` module:

```elixir
def get_all_by(queryable, keyword, opts \\ []) when is_list(keyword) and is_list(opts) do
  require Ecto.Query
  all(Ecto.Query.where(queryable, ^keyword), opts)
end
```
