### ISSUE TITLE
Do not make queries in Ecto worker

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#585]

**Comment by fishcakez** [comment]
I would like to pick this up by adding more callbacks to the `Ecto.Adapters.SQL.Connection` behaviour and removing `connect`, `disconnect` and `query`.

```elixir
defcallback init(any) ::
  {:ok, any} | {:stop, any}

defcallback handle_connect(any) ::
  {:ok, any} | {:stop, any} | {:reconnect, any}

defcallback handle_handshake(any) ::
  {:ok, any} | {:ok, any, timeout | :hibernate} | {:stop, any} | {:reconnect, any}

defcallback handle_query({String.t, list, Keyword.t}, {pid, {pid, any}}, any) ::
  {:reply, any, any} | {:reply, any, any, timeout | :hibernate} |
  {:noreply, any} | {:noreply, any, timeout | :hibernate} |
  {:stop, any, any} | {:stop, any, any, any} |
  {:reconnect, any, any} | {:reconnect, any, any, any}

defcallback handle_info(any, any) ::
  {:noreply, any} | {:noreply, any, timeout | :hibernate} |
  {:stop, any, any} | {:reconnect, any, any}

defcallback code_change(any, any, any) :: {:ok, any}

defcallback terminate(any, any) :: any
```

This will allow Ecto to wrap the SQL drivers and convert begin/all/rollback/savepoint etc on the same connection process to a query and then call `handle_query`. `begin`/`rollback` would also trigger a monitor/demonitor of the client.

Ecto would also handle the queuing of queries so that only one query is handled at a time - as all the SQL drivers implement this. The `from` term in `handle_query/3` is `{caller, {self() tag}}`, which allows a message to be sent to `self()` dequeue the next item on reply. This may change slightly on implementation but the idea will be similar and was stolen from an ack'ing idea of @josevalim.

The `reconnect` tuples would be used to trigger a reconnection attempt, while maintaining the same state. However all queries would be replied to with an noconnection exception until a successfully connection occurred. It may also do backoff or other features but we can worry about those later.

The above features will:

* Merge the Worker and Connection processes
* Make drivers independent of pooling strategy (in future can support multiple poolling strategies without changing the driver implementations)
* Remove duplicate code between drivers (will tidy up implementations considerably)

Of course if Ecto did all of the above it would make drivers useless outside of Ecto. Therefore before adding this to Ecto there would be an `SQLConnection` behaviour outside and unrelated to Ecto that adds all the above features except would not handle begin/rollback/etc and would have a more generous handle_query/3 spec. This preliminary work would be done inside a fork of one of the drivers (postgrex @ericmj).

Once completed it would be moved to its own project and then added to other drivers. At this stage if it proves a useful pattern and any kinks have been ironed out we might be able to generalise the behaviour to `Connection` and rename `handle_query` so that it is nolonger SQL specific. I know there are several projects that could make use of something like this.

Finally it would be added to Ecto and workers/connections merged.

After that work can begin on supporting multiple pooling strategies.

**Comment by josevalim** [comment]
Please go ahead @fishcakez . I am confident you would do a better job than me and making it SQL independent was on the roadmap too! :heart:
