### ISSUE TITLE
Should ecto supports more iso8601 input formats?

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/ecto#613]
Make it sense to have default behaviour, to casting timezone information(as supported in iso8601) to universaltime with Ecto.DateTime?

```elixir
Ecto.DateTime.cast("2015-12-31T12:00:00+0100")
%Ecto.DateTime{day: 31, hour: 11, min: 0, month: 12, sec: 00, usec: 0, year: 2015}
```

Hopefully, it is not confusing, but may be good default behaviour for dealing with input sources from iso8601-compatible non-timezone datatype.

**Comment by liveforeverx** [comment]
Yes, a question for the case, if it is not needed to deal with timezones at all(there is no need to download tzdata). Use case (may be very rare?) only to accept iso8601 and save it in UTC to what Ecto.DateTime is good for.

But seems, like Calecto, doesn't support it too, in that form:

```elixir
Calecto.DateTime.cast("2015-12-31T12:00:00+0100")
** (FunctionClauseError) no function clause matching in Calecto.DateTime.cast/1
    (calecto) lib/calecto/date_time.ex:25: Calecto.DateTime.cast("2015-12-31T12:00:00+0100")
```

**Comment by lau** [comment]
Thanks for cc'ing me @josevalim , I love these datetime problems :)

As it is today it seems that a Ecto.DateTime is what I would call "timezone naive" struct. It does not claim to be in a specific timezone. It does not claim to be UTC. If casting would work like in the example, it would mean that DateTime would be treated as UTC. But not everyone uses Ecto.DateTime for only UTC. If you use the wall time in the database, then you would not want to compare it to UTC.

So I think it could add confusion to add that functionality as described. Implicitness over explicitness has a danger of adding confusing, unexpected behavior and bugs that are hard to track down.

I would not the feature as it is described.

### Calendar + Calecto approach
What I have done with [Calecto](https://github.com/lau/calecto) is that if you have a :datetime type in your database, you can choose between two Ecto types in the schema: NaiveDateTime or DateTimeUTC. The idea is that the programmer is making a conscious choice between the two and that the associated functionality doesn't silently and magically do something unexpected that would be inappropriate for the chosen type.

You could parse the string as UTC. And then you have a DateTime that you could save in Ecto to a field that is set to be Calecto.DateTimeUTC.

```
> Calendar.DateTime.Parse.rfc3339_utc("2015-12-31T12:00:00+01:00")
{:ok,
 %Calendar.DateTime{abbr: "UTC", day: 31, hour: 11, min: 0, month: 12, sec: 0,
  std_off: 0, timezone: "Etc/UTC", usec: nil, utc_off: 0, year: 2015}}
```
Note that I have changed the string by adding a colon in the offset ("+01:00" instead of "+0100") to make it RFC 3339 compliant.

**Comment by liveforeverx** [comment]
Thanks for explanation, I've thought, that it can be a reason.

Ok, I need to do it with my own type, or contribute to Calecto with iso8601 parse support, but it will be explicitly parsed, not casted? iso8601 supports +0100, and I do not have any influence on sender.

I've read about year or so a blog post, which have say, that if you do some service for people over all world and need to deal with time(for example calendar with notifications), you need to save DateTime in UTC, Local Time, Timezone(not enough) and geographic location(some geographic locations can/have changed timezone).

**Comment by josevalim** [comment]
Thanks for the input @lau.

**Comment by lau** [comment]
@liveforeverx If you haven't yet, check out this blog post: http://www.creativedeletion.com/2015/05/10/the-need-timezones.html And the other ones on the blog from this year related to time.

You could write your own ISO8601 parser, that produces a tuple that Ecto.DateTime.from_erl can use.
 
I have just updated Calendar to also support parsing of timestamps where there is no colon in the offset. So now you could also parse it with Calendar:
```
Calendar.DateTime.Parse.rfc3339_utc("2015-12-31T12:00:00+0100")
{:ok,
 %Calendar.DateTime{abbr: "UTC", day: 31, hour: 11, min: 0, month: 12, sec: 0,
  std_off: 0, timezone: "Etc/UTC", usec: nil, utc_off: 0, year: 2015}}
```
Then you can either use that with an Ecto field set to Calecto.DateTimeUTC. Or take that DateTime and call Calendar.DateTime.to_erl to get an erlang style tuple that can be used with Ecto.DateTime.from_erl.

@josevalim Any time.
