### ISSUE TITLE
Default primary key

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ecto#619]
By default in Ecto the primary key is `id`. In MongoDB that I will be integrating it is `_id`, and as far as I can tell it cannot be changed. 

We should discuss how to address this issue. Should there be some way to allow adapters inject code into models (I'm not sure that it's a good idea), or maybe everybody should specify the different primary key by hand in each model. Maybe there's another way?

/cc @josevalim @ericmj

**Comment by josevalim** [comment]
I thought a little bit about this and I believe the best option is to automatically translate "_id" to whatever primary key is being used by the model. This may require changes to the adapter so they receive this kind of information but it is the closest we can get to have it working transparently.

**Comment by josevalim** [comment]
Thoughts?

**Comment by michalmuskala** [comment]
Such translation would solve the problem with the key name, but what about it's type?
By default it's integer, in mongo it's ObjectID that is basically a 12 byte structured binary.
The same issue would arise with the default foreign key type.

What about the mongo adapter defining it's own base model module like this:
```elixir
defmodule MongodbEcto.Module do
  defmacro __using__(_) do
    quote do
      use Ecto.Model
      @primary_key {:_id, :objectid, read_after_writes: true}
      @foreign_key_type :objectid
     end
   end
end
```

Then instead of using `Ecto.Model` one would use `MongodbEcto.Model`

**Comment by josevalim** [comment]
Yes, we should also consider the type.

At first, I would like to avoid things like `MongodbEcto.Model` because it can then becomes a escape goat. It would allow us to hide everything that is not compatible inside it. So I think we should avoid it as much as we can.

One idea is to introduce the :id type (or :binary_id). It is not a UUID but it is also not an Object ID. It is synonymous to a binary field which is taken care by the database. So validation and checking happens at the adapter level. Something else to discuss is if :id fields should be automatically set by the adapter / db. I am sure MongoDB is going to impose a couple things on this area, so we don't need to worry about it, we will come up with the requirements as we go.
