### ISSUE TITLE
:binary_id should be wrapped in Ecto.Query.Tagged

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-lang/ecto#675]
Having a problem in TDS where binary_id's need to be explicitly identified for casting purposes. :binary_id's should be wrapped in Ecto.Query.Tagged instead of being presented as standard binary.

**Comment by josevalim** [comment]
Fixed on master. Please let me know if it works and, once it does, I will release Ecto v0.12.1. Also note that master has a new map type. In order to support it, you just need to do the same changes as we did to the mysql driver: https://github.com/elixir-lang/ecto/commit/6f6b300273d352a326c040f66b7c849ace7e5474#diff-975ad8a7b1f8e27ac59595bcdbdd0a07

Do not encode it as XML because apparently JSON support is coming to SQL Server 2016.
