### ISSUE TITLE
Support new update syntax

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#715]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite3
* [x] Mongo

We have a new update syntax in Ecto master. Here is the whole pull request #714 although SQL databases only need to replicate the changes done to postgres:

* `update_all/2` is now `update_all/1`: https://github.com/elixir-lang/ecto/pull/714/files#diff-ee25bf8df5589fbf812f652738bfbdae
* The new tests: https://github.com/elixir-lang/ecto/pull/714/files#diff-b5e45273b9fb2c6589ceb1293bda1d96

As soon as all adapters catch up on this, we will start the process to get v0.13.0 out.

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/9f57440f0b30d2b1eee0433ea182316c88fe501d

@josevalim I had to exclude `:strict_savepoint` to get the most recent integration tests to pass.  Would you mind briefly explaining what "strict savepoints" are in Postgres?  I couldn't find any references to them.  I just want to make sure that I'm excluding them because they are not supported and not because I have overlooked implementing them.

**Comment by josevalim** [comment]
@jazzyb strict_savepoint: Issueing a savepoint outside of a transaction should fail. We don't rely on this behaviour in the code per-se, but in order to test for race conditions in the pool, we need it. So you are fine.

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@ae5a2e40fa09f9a4df6ad1f57c677bf99514b324

**Comment by mobileoverlord** [comment]
Man @jazzyb I really tried to get a "first" on that one and you snuck in sqlite support first again! :stuck_out_tongue:

**Comment by jazzyb** [comment]
@mobileoverlord I was only first because I have a lot of chores I need to do and welcomed the distraction :)

**Comment by michalmuskala** [comment]
Mongo: michalmuskala/mongodb_ecto@71db151

**Comment by josevalim** [comment]
You folks are on fire!
