### ISSUE TITLE
Handle decimal in query expressions

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#764]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite

It is just a matter of adding this clause: https://github.com/elixir-lang/ecto/commit/f96e6028c6e25fc508b4ed39a67ef1a6b9248ce5#diff-975ad8a7b1f8e27ac59595bcdbdd0a07R355

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@8d1c9f8959e61281600ddd5d76bb836765d680e9

**Comment by jazzyb** [comment]
Couple of questions:

Firstly, I'm trying to write a unit test for the Decimal case, but this code:

```elixir
  test "decimals" do
    query = Model |> select([], Decimal.new(123.0)) |> normalize
    assert SQL.all(query) == ~s{SELECT 123.0 FROM "model" AS m0}
  end
```

gives me this error:

```
** (Ecto.Query.CompileError) `Decimal.new(123.0)` is not a valid query expression
    (ecto) expanding macro: Ecto.Query.select/3
    test/sqlite_ecto_test.exs:425: Sqlite.Ecto.Test."test decimals"/1
    (elixir) expanding macro: Kernel.|>/2
    test/sqlite_ecto_test.exs:425: Sqlite.Ecto.Test."test decimals"/1
```

What is an example query expression I could use to test the Decimal change?

Secondly, I'm getting the following error when I try to run integration tests with the newest commit in master:

```
** (ArgumentError) argument error
    (stdlib) :lists.keyfind(:adapter, 1, [{:pool, Ecto.Pools.Poolboy}, {:size, 1} | nil])
    (elixir) lib/access.ex:49: Access.List.get/2
    (ecto) lib/ecto/repo/config.ex:10: Ecto.Repo.Config.parse/2
    deps/ecto/integration_test/cases/pool.exs:16: (module)
    deps/ecto/integration_test/cases/pool.exs:15: (module)
```

Code is [here](https://github.com/jazzyb/sqlite_ecto/tree/test-errors).  I looked at the changes to the `test_helper.exs` scripts for Postgres and MySQL, and I don't see any obvious differences.  Any ideas what the problem is?

**Comment by josevalim** [comment]
> Firstly, I'm trying to write a unit test for the Decimal case, but this code:

You don't need to right one as we already have tests in the `integration_test/cases/types.exs`. Something like:

    from p in Post, where: p.some_decimal == 1.0

will convert 1.0 to Decimal.

> Code is here. I looked at the changes to the test_helper.exs scripts for Postgres and MySQL

Maybe an issue based on how things are being loaded? I have improved the error message but the issue is that it can't find the config for Ecto.Integration.TestRepo.

**Comment by jazzyb** [comment]
Thanks for the help, José!

I had `Application.put_env(:sqlite_ecto, ...` instead of `Application.put_env(:ecto, ...` for both `TestRepo` and `PoolRepo`.  I don't know how I got away with that one for so long.

SQLite: https://github.com/jazzyb/sqlite_ecto/commit/a2a48d84ce955bea40c45f6c5117912538bbc31a
