### ISSUE TITLE
Support array operations in update

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#786]
Now that we released the new update syntax, we can start supporting more operations. Here is the PostgreSQL list:

http://www.postgresql.org/docs/9.1/static/functions-array.html

@michalmuskala where is the list for MongoDB? I think we can at least support concat or push?

**Comment by michalmuskala** [comment]
Here's a list: http://docs.mongodb.org/manual/reference/operator/update/

We could support `mul` for numeric fields (since Mongo 2.6), for arrays we could support append, prepend (>= 2.6) and concat. Please not that in Mongo those can only be used with constant values (no columns, fields, etc - but we're already dealing with that problem).

**Comment by josevalim** [comment]
Sweet, I think we can support $push and $pull.

**Comment by josevalim** [comment]
In master.
