### ISSUE TITLE
Support constraints

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#865]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] PostgreSQL
* [x] MSSQL
* [x] SQLite
* [x] MongoDB

Ecto master has added support to convert database constraints into changeset errors. SQL adapters just need to convert errors into constraints information. If your database provides structured errors, you can just copy Postgres:

https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/postgres/connection.ex#L40-L45

Otherwise you may need to extract information from the error message as in MySQL:

https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/mysql/connection.ex#L38-L58

If you are not using a SQL database, the difference is that `insert`/`update`/`delete` in the adapter may return `{:invalid, constraints}`.

This is the one of 2 changes before Ecto v1.0! Integration tests have been added, please try to make them pass ASAP so we can release Ecto v0.16.0. Notice this feature depends on #863.

**Comment by elbow-jason** [comment]
Oh cool! Much better than simply crashing the process.

**Comment by jazzyb** [comment]
@josevalim I have a few questions about the constraint integration tests:

*  When I get a unique constraint error, SQLite returns a message like `"UNIQUE constraint failed: posts.uuid"`.  However, [this assertion in the integration tests](https://github.com/elixir-lang/ecto/blob/master/integration_test/cases/repo.exs#L205) is failing because it is apparently looking for a return value of `[unique: "posts_uuid_index"]` from `to_constraints/1` instead of `[unique: "posts.uuid"]`.  Is this a mistake with the test, or do PG and MySQL return the name of the index instead of the column?

* When I comment out the above assertion to see if my code passes the rest of the test, [this line](https://github.com/elixir-lang/ecto/blob/master/integration_test/cases/repo.exs#L221) raises:
```
     ** (Ecto.ConstraintError) constraint error when attempting to insert model:

         * unique: posts.uuid

     If you would like to convert this constraint into an error, please
     call unique_constraint/3 in your changeset and define the proper
     constraint name. The changeset defined the following constraints:

         * unique: posts_uuid_index
```
(Notice that it identified the `posts_uuid_index` value this time.)  In what circumstances is `{:error, changeset}` returned versus raising `Ecto.ConstraintError`?

* In the case of foreign key constraint errors, SQLite provides the very unhelpful message `"FOREIGN KEY constraint failed"` -- no idea *which* constraint failed.  Is it worth having `to_constraints/1` return anything in this case (`[foreign_key: nil]` perhaps?), or should I just ignore all the `:foreign_key_constraint` tests?

Reference code:  https://github.com/jazzyb/sqlite_ecto/commit/cc2cebd700b2095dc2194d8c2cd548fece0c99df

**Comment by josevalim** [comment]
@jazzyb those are very good questions. If you are having them now, it means we need to straight some things out in the API. Let's start:

>  Is this a mistake with the test, or do PG and MySQL return the name of the index instead of the column?

Both PG and MySQL return the index name in the error. That's because the same column can have multiple indexes.

> In what circumstances is {:error, changeset} returned versus raising Ecto.ConstraintError?

The error message says: "If you would like to convert this constraint into an error, please call unique_constraint". So unless you have mapped that constraint to a changeset constraint, we are going to raise. Does it make sense? Could we make this clearer?

> should I just ignore all the :foreign_key_constraint tests?

You will have to ignore the tests. Apparently the unique constraint tests too. :( I am wondering now if we should raise or just ignore when giving constraints to databases like sqlite3 and mongo. @jazzyb and @michalmuskala, thoughts?

**Comment by michalmuskala** [comment]
I can have unique constraints without any problems. As for the foreign key ones - I'm ignoring the whole body of `create` calls in migrations - so I’m already ignoring the constraints.

**Comment by jazzyb** [comment]
Based on my testing I would vote for returning a blank in SQLite:

```elixir
def to_constraints(_), do: []
```

This allows the original errors to be raised.

**Comment by josevalim** [comment]
@jazzyb that sounds like a plan. Thanks @jazzyb.

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/37a4b6a4996b99fe7b50ff92e02928f2926e2759

**Comment by michalmuskala** [comment]
MongoDB: https://github.com/michalmuskala/mongodb_ecto/commit/d9e721b2b1ea7ef2e4f7d6c383f8c79019e359d3 and https://github.com/michalmuskala/mongodb_ecto/commit/51dec3796587fc0190548c2718c8df5bc0720ec0

**Comment by josevalim** [comment]
@jazzyb @michalmuskala btw, if any of the constraints can silently fail, which I think is the case for mongo ecto, just make it really clear in the readme.

**Comment by michalmuskala** [comment]
I would prefer to be able to raise if you give anything to the `create` function in migrations - that way there will be no expectation of support for foreign keys, as you won't be able to even put them in place. Giving fields there makes no sense for MongoDB whatsoever - I just skip them now.
I can't do this now because of the `schema_migrations` table. Should I maybe special case it? Or maybe go through the table fields, and raise if any of them is a `references` one?

**Comment by josevalim** [comment]
Raising or warning for references is a good alternative. Raising is
probably better for now, we can always revisit later.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by mobileoverlord** [comment]
MSSQL is ready, however, I am failing some tests because of index naming. This is kinda picky but foreign key constraint naming standards for sql server are FK_col_name but the integration tests are expecting col_name_fkey which seems to be the naming convention for PG. Should I change to adpot that naming convention?

**Comment by josevalim** [comment]
@mobileoverlord yes, we will need to normalize on one convention and I went with postgres one. So :+1: for adopting this convention. A huge part of this PR is exactly using the PG convention when no name is given (we use it for PG, MySQL and all others from now on).

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@5bd6b2a97e20fd5627d139d268e37eb4f6434a48
