### ISSUE TITLE
BelongsTo association does not use proper related key

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/ecto#908]
The following fails: https://gist.github.com/bcardarella/06184cf78c45f2cfd1b9

`Ecto.Association.BelongsTo` uses the `module`'s primary key instead of the related module's primary key: https://github.com/elixir-lang/ecto/blob/7647caca0fc71badf5e5270b63f834ef38a7bfcb/lib/ecto/association.ex#L580

I can put together a quick PR for this if you'd like

**Comment by josevalim** [comment]
@bcardarella we can't fix it. Maybe we can improve the docs.

The issue is that the modules cannot depend on each other at compilation time because it could lead to deadlocks. So the best we can do is to assume they are using the same primary key structure, otherwise, you need to explicitly specify it.

**Comment by bcardarella** [comment]
@josevalim what about instead of the assumption if the owner module's primary_key has been overridden and there is no `references` option a warning is raised, or it would be required to pass `reference` if `primary_key` is overridden?

**Comment by josevalim** [comment]
I am ok with adding a warning now and leave a TODO so in the future we always raise or we simply default to `:id`.

**Comment by josevalim** [comment]
Actually, we should warn now only if the column is different than `:id`. In the future, we should always default it to `:id`.

**Comment by Licenser** [comment]
I'm curious, from the last comment on this issue I undwerstand that the default should be `:id` for the reference, but it seems like, while a warning is raised, the primarykey is picked as a refereence key isntead?

**Comment by josevalim** [comment]
@Licenser you are correct. We kept the previous behaviour because changing it would be backwards incompatible. So we emit the warning if they are different but still default to the actual primary key. We print the primary key we are using in the error message too.

The question is, now that we are working on Ecto 2.0, should we keep with the warning or should we effectively default to :id?

**Comment by Licenser** [comment]
My feeling is defaulting the the primary key in this collection is wrong, defaulting to :id seems more sensible. The reasoning is tha that for the belongs-to side the primary key does have no effect on the relation (it doesn't even need one?).

Another alternative, given the we can't know for sure what the remote sites key is, would be forcing the user to always provide one, this would remove all confusion, but admittedly be a bit more work?

**Comment by josevalim** [comment]
> My feeling is defaulting the the primary key in this collection is wrong, defaulting to :id seems more sensible.

Yes, that was the original rationale, so we should rather go with it. Now we are preparing for Ecto 2.0, it is the perfect time to do this change, so we should do just that. 

Thank you for the feedback!

**Comment by Licenser** [comment]
Awesome :) tahnks for the hard work!
