### ISSUE TITLE
Custom message for a missing required field

### ISSUE THREAD

**Issue by leikind** [elixir-lang/ecto#915]
I wanted to specify a custom message for a missing required field, and found out that it is hardcoded deep in Ecto: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/changeset.ex#L459 without a way to modify it.

There is also no separate `validate_required` function which would add a field to the list of required fields in the `Ecto.Changeset` struct, perform the validation, and allow to specify a custom message. `cast` just does too much stuff without exposing it as public functions, don't you think so?

**Comment by josevalim** [comment]
@leikind we plan to introduce an API for I18n, which will allow customization of error messages. Today you can simply traverse the errors list and replace the "can't be blank" message by whatever you want.

> cast just does too much stuff without exposing it as public functions, don't you think so?

I agree that checking for required fields is not necessarily part of cast. It has, however, been implemented like that so you don't end-up specifying fields multiple times. Otherwise you would end-up with code like this:

```elixir
model
|> cast(params, ~w(field_a field_b field_c field_d), ~w(field_e field_f))
|> validate_required(~w(field_a field_b field_c field_d))
``` 

Furthermore, in order to check if a field is required, we also need to look at the model value, an operation which does not happen with the other validations, as they rely solely on changes.
