### ISSUE TITLE
Consider deprecating giving models to update

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#937]
There are a bunch of issues when we do such due to the lack of dirty tracking. If we deprecate or warn on this behaviour, we are going to ensure better use of Ecto.

/cc @ericmj @michalmuskala

**Comment by josevalim** [comment]
The reason we do not need to do it on insert (nor delete) is because there is no need for dirty tracking in such cases.

**Comment by michalmuskala** [comment]
I would be for this change. Allowing models in update, does make it hard to do some things, especially associations, and may be confusing in some circumstances. Probably, this also has a performance impact, because we need to send entire models to the database. 

I'm only afraid that it's a breaking change, and we're now after 1.0. I'm not sure how widely used this is.

**Comment by ericmj** [comment]
I agree on deprecating it, but I would wait until we are closer to 2.0. Runtime warnings of deprecations are really annoying since they heavily pollute your logs meaning that for many it's effectively a breaking change because it needs to be fixed immediately.
