### ISSUE TITLE
Ecto.Changeset.validate_length/3 does not work on empty array fields

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ecto#981]
Because array fields have default of `[]`, when an empty list is passed to cast no change is made. Because `validate_length` uses `validate_change` the validation is not applied.

**Comment by josevalim** [comment]
Closing in favor of #1129

**Comment by mgwidmann** [comment]
Ran across this issue recently, changing the default doesn't actually fix the issue. As @michalmuskala points out, an array with default of `nil` which is unchanged (during an insert operation for example) will not have the `validate_length(:array, min: 1)` rule applied to it. Because `validate_change` only looks at the field *if it has been changed*, fields which are unchanged are not validated.

Testing this, a string field which uses `validate_length(:password, min: 8)` on a brand new record will allow the password to remain blank unless a `validate_required([:password])` accompanies it... IMHO this line https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/changeset.ex#L1467 should be always run and *not* wrapped around a `validate_change` call.

Why was this implemented this way?

**Comment by michalmuskala** [comment]
It works correctly now. If you want a field to be required than the function you want to run is, well, `validate_required/2`. All other validations validate a particular value - until it's in changes, there's no value to validate, so it doesn't make sense to run the validation - `validate_length` is no exception here.
