### ISSUE TITLE
Document query and model prefix

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ecto#985]
We have this feature for some time now, but it seems it's not documented. We should explain how to use prefix for queries and for models.

**Comment by Dania02525** [comment]
I asked the question on SO,  I think I have this figured out.  The only thing is, to use prefix on repo functions, the model needs to already be a query.

This is what I've got:
Model 
|> Ecto.Queryable.to_query
|> Map.put(prefix: "whatever")
|> Repo.all

Since the model is not accepted by repo functions after building it like %Model{}.  If you want to point me in the directions of how to contribute to the docs, I can add what I've learned.

**Comment by josevalim** [comment]
Thank you @Dania02525! I would add a "## Query Prefix" section around here in the docs: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/query.ex#L106 and we should be good to go!
